### ISSUE TITLE
unsuccessful attempt with textadept

### ISSUE THREAD

**Issue by cbertelli** [xiaozhuai/rmate-server#6]
Hello,
I used rmate-server on MacOS 10.14 with the command line call for TextAdept which is **ta**.
After running 
```
local:$ ./rmate-server -c textadept.json &
```
and, after connecting to my web server, I issued the usual
````
server:$ rmate deleteme7g.php

new session IPv4://127.0.0.1:50865
[user@myserver ~]$ onMessage: open, {"display-name":"myserver:deleteme7g.php","real-path":"/home/user/deleteme7g.php","data-on-save":"yes","re-activate":"yes","token":"deleteme7g.php","data":"21356"}, 21356
local tmp file: /var/folders/bs/jy_ww7jn0gdd778nw96_pynr0000gn/T/rmate-server/588f3043a17e48796e1d7f40a1d1cf7dfdb4700c/deleteme7g.php
Error: editor process exited so quickly, it must be blocked while editing
 at ChildProcess.<anonymous> (/snapshot/rmate-server/src/RemoteFile.js:113:35)
 at ChildProcess.emit (events.js:315:20)
 at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
````
Despite the error, **ta** opened a new buffer on TextAdept with the content of the remote file.

After modifying the buffer, I saved it with no detectable error, but the original file was not updated.

The config was a copy of the examples:
```
{
    "host": "127.0.0.1",
    "port": 52698,
    "editor": {
        "command": "mate",
        "args": [
            "-w",
            "{{file}}"
        ]
    }
}
```
Apparently the temporary file created by rmate-server did not get its way back to the server.
Do you have any suggestion

**Comment by xiaozhuai** [comment]
Hello @cbertelli , please try `rmate -w deleteme7g.php`

**Comment by xiaozhuai** [comment]
BTW, `textadept` is a editor, am I right?
Then you should change the json to provide the right command. (Maybe `ta`?)
```json
{
    "host": "127.0.0.1",
    "port": 52698,
    "editor": {
        "command": "mate",
        "args": [
            "-w",
            "{{file}}"
        ]
    }
}
```

**Comment by xiaozhuai** [comment]
Update:
I download TextAdept and found `ta` is just a shell script.
```bash
#!/bin/bash
# Copyright 2007-2022 Mitchell. See LICENSE.

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
  echo "ta - shell script to launch Textadept.app"
  echo "Usage:"
  echo "ta [filenames]         open the given filenames in Textadept"
  echo "ta [args] [filenames]  open the given filenames in a new instance of"
  echo "                       Textadept with the given arguments"
elif [ "${1:0:1}" == "-" ]; then
  open -n -a Textadept.app --args "$@"
else
  open -a Textadept.app "$@"
fi
```

There is no `wait` (Usually `-w`) option. rmate-server cannot work in this situation
But luckly, you can set command to `/Applications/Textadept.app/Contents/MacOS/textadept_osx`, it enables `wait` by default.

So, change you json to below and check if it works. : )
```json
{
    "host": "127.0.0.1",
    "port": 52698,
    "editor": {
        "command": "/Applications/Textadept.app/Contents/MacOS/textadept_osx",
        "args": [
            "{{file}}"
        ]
    }
}
```

**Comment by cbertelli** [comment]
Thank you very much. I noticed that I didn't use the -w which is required, but it didn't work. I did not remember that ta was a bash script. The solution works well.

**Comment by xiaozhuai** [comment]
Happy to hear that. I will close this issue as completed.
